ams:
    build: .
    domainname: ams.dev
    hostname: mediaserver
    #command: /start.sh --disable-access-log
    ports:
        - "1935:1935"
        - "1111:1111"
        - "443:443"
        - "80:80"
